### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by lizzxrd** [tgabi333/youtrack-article-export#1]
Greetings!
Just found out your project and it seems really helpful for me but I encounter some problems with it.
I work on Ubuntu 22.04 
When I\`m trying to export article from my Knowledge Base by `node concat.js --id <my_arcticle_ID>`  the project fails with:
```
downloading attachment: <my_arcticle_ID> 20240618

/root/youtrack-article-export/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310

                reject(new Error([

                       ^
Error: Failed to launch the browser process! undefined

[7147:7147:0619/144944.635184:ERROR:zygote_host_impl_linux.cc(99)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/root/youtrack-article-export/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)

    at ChildProcess.emit (node:events:529:35)

    at ChildProcess._handle.onexit (node:internal/child_process:292:12)

```

The Internet says that i should add --no-sandbox argument like this:
```
const browser = await puppeteer.launch({
    headless:false,
    args: ["--no-sandbox"]
});
```
or to tell Puppeteer where is chromuim location:
```
const browser = await puppeteer.launch({
  executablePath: '/usr/bin/chromium-browser'
})
```
But i don`t really get where exactly should I make these changes. Maybe you could help me out?

**Comment by tgabi333** [comment]
Hi @lizzxrd !

You could try changing this line:
https://github.com/tgabi333/youtrack-article-export/blob/e19ae30427ec3dec6024de46a720aa4c8f7439d1/lib/helpers/generatePdf.js#L108

to:

```js
    launch_options: { headless: 'new', args: ['--no-sandbox'] },
```

**Comment by lizzxrd** [comment]
Thank you very much! I`ve figured out how to make your project work :)
Actually I changed the line this way:
```
   107   const html = await mdToPdf(article, {

   108     launch_options: { headless: 'new', args: ['--no-sandbox'], executablePath: '/usr/bin/chromium-browser'},
```
There`s another line in the file that i changed this way: 
```
    124   const pdf = await mdToPdf(article, {

    125     launch_options: { headless: 'new', args: ['--no-sandbox'], executablePath: '/usr/bin/chromium-browser'},
```
And most importantly I did it in both `generatePdf.js` AND `generateHtml.js`
